apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: autorender
    weavescope-component: network-control-plugin
  name: network-control-plugin
spec:
  template:
    metadata:
      labels:
        app: autorender
        weavescope-component: network-control-plugin
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: network-control-plugin
          image: billyzhang2010/network-control-plugin:latest
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: scope-plugins
            mountPath: /var/run/scope/plugins
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: scope-plugins
        hostPath:
          path: /var/run/scope/plugins
